### ISSUE TITLE
Add position option

### ISSUE THREAD

**Issue by ChaudhryAtif** [craftpip/angular-confirm#8]
Ability to show the dialog at different places of the screen.
- top-left
- top-center
- top-right
- center-left
- center (default)
- center-right
- bottom-left
- bottom-center
- bottom-right

**Comment by craftpip** [comment]
Some of these options are not possible because of the bootstrap setup,
and angular-confirm's self centering thing.

Possible:
top-left, top-center, top-right, center-left, center, center-right

Not possible: 
bottom-left, bottom-center, bottom-right

`alignMiddle` property determines of the modal is going to be in the center or top
`columnClass` property determines the bootstrap column

example: 
top-left:
```js
columnClass: 'col-md-4',
alignMiddle: false,
```
top-right:
```js
columnClass: 'col-md-4 col-md-offset-8',
alignMiddle: false,
```

**Comment by craftpip** [comment]
The problem with the bottom position is that angular-confirm's content,
the content increases and goes out of the window, and has to scroll.
bottom positioning will cause bad UX

**Comment by ChaudhryAtif** [comment]
Could there be an option to define or ensure fixed height when positioning it at the bottom? For example, if I have a dialog with 3 input fields (or fixed content), the size will most likely stay constant.

**Comment by craftpip** [comment]
This can be done, but it will take time. 
i will add this to my todos. 👍

**Comment by ChaudhryAtif** [comment]
Sounds good. Thanks!
